### ISSUE TITLE
Correção Exercício `0.7.1`

### ISSUE THREAD

**Issue by mathiasgheno** [RobsonGomes347/exercicio.0.7.1#1]
# Correção Exercício `0.7.1`

> Faça o layout do wireframe abaixo usando flexbox.  [Referência visual](https://i.imgur.com/jDDModP.png). 

Faltou aplicar a centralização vertical, foi aplicada apenas o horizontal. Para isso basta atribuir altura para o seu `html` e uma largura para o sey `body`. 

```css
html {
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 0;
}

.conteiner {
    width: 500px;
}

```

**Nota:** 8.5
